### ISSUE TITLE
`Ctrl-o` (`operate-and-get-next`) triggers a Segmentation fault on Termux on Android

### ISSUE THREAD

**Issue by faneca** [0xf4/pythonrc#4]
Wondering if this could also happen on OS X or any other environments.

**Comment by 0xf4** [comment]
Thanks for the report. 
I tried solving it with the following patch (which works as equally fine on Linux as the unmodified version, both on python2 an python3, and is more strictly *ctype-hinted*, hence "theoretically better"):
```diff
diff --git a/pythonrc.py b/pythonrc.py
index 397093e..92e0004 100644
--- a/pythonrc.py
+++ b/pythonrc.py
@@ -460,13 +460,14 @@ def init():
         # We'll hook the C functions that we need from the underlying
         # libreadline implementation that aren't exposed by the readline
         # python module.
-        from ctypes import CDLL, CFUNCTYPE, c_int
+        from ctypes import CDLL, CFUNCTYPE, c_int, c_char_p
 
         librl = CDLL(readline.__file__)
         rl_callback = CFUNCTYPE(c_int, c_int, c_int)
         rl_int_void = CFUNCTYPE(c_int)
+        rl_add_clbk = CFUNCTYPE(c_int, c_char_p, rl_callback, c_int)
 
-        readline.add_defun = librl.rl_add_defun # didn't bother to define args
+        readline.add_defun = rl_add_clbk(librl.rl_add_defun)
         readline.accept_line = rl_callback(librl.rl_newline)
         readline.previous_history = rl_callback(librl.rl_get_previous_history)
         readline.where_history = rl_int_void(librl.where_history)
@@ -490,7 +491,7 @@ def init():
             return result
 
         # Hook our function to Ctrl-o, and hold a reference to it to avoid GC
-        readline.add_defun('operate-and-get-next', operate_and_get_next, ord("O") & 0x1f)
+        readline.add_defun(b'operate-and-get-next', operate_and_get_next, ord("O") & 0x1f)
         history._readline_functions = [operate_and_get_next]
 
     except (ImportError, OSError, AttributeError) as e:
```

...but now, on termux, it segfaults when **registering** the function (i.e. when calling `readline.add_defun`) instead of when invoking `operate_and_get_next` by pressing `Ctrl-o`. Anyway, the segfault in the non-patched case happens before any single line of the registered function is executed, so there's something definitely funky on the registration process).

**Comment by 0xf4** [comment]
I think this excerpt from the [ctypes documentation](https://docs.python.org/3/library/ctypes.html#callback-functions) can be relevant:
> Also, note that if the callback function is called in a thread created outside of Python’s control (e.g. by the foreign code that calls the callback), ctypes creates a new dummy Python thread on every invocation. This behavior is correct for most purposes, but it means that values stored with threading.local will not survive across different callbacks, even when those calls are made from the same C thread.

Perhaps this works in Linux just by chance, and breaks on other platforms. I wish someone with an OS X or a Windows at hand tried this repository.

**Comment by 0xf4** [comment]
Actually, this is more complicated and waay out of my control. I've put gdb to the task and it seems the access violation occurs when preparing the FFI call. In GNU/Linux, `x86_64` arch, the call to ` ffi_closure_unix64` looks like this (and works perfectly):
```sh
$ gdb --eval-command=run python
```
```python
(...)
>>> from ctypes import c_int, c_void_p, CFUNCTYPE, c_char_p, cast
>>> hex(cast(history._readline_functions[0], c_void_p).value)
'0x7ffff7fee0f0'
>>> ^Z
```
```gdb
Program received signal SIGTSTP, Stopped (user).
(...)
(gdb) x/4i 0x7ffff7fee0f0
   0x7ffff7fee0f0:	movabs $0x7ffff633ef62,%r11
   0x7ffff7fee0fa:	movabs $0x7ffff7fee0f0,%r10
   0x7ffff7fee104:	clc    
   0x7ffff7fee105:	rex.WB jmpq *%r11
(gdb) disass 0x7ffff633ef62
Dump of assembler code for function ffi_closure_unix64:
   0x00007ffff633ef62 <+0>:	lea    -0xc8(%rsp),%rsp
(...)
```
If I do the same in Termux, with this compilation of Python:
```
Python 3.6.2 (default, Jul 19 2017, 11:01:41)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
```
the `arm` code preparing the call to `ffi_closure_SYSV` looks like this:
```gdb
(gdb) x/3i 0x556461ae80
   0x556461ae80:        ldr     x16, 0x556461ae8c
*  0x556461ae84:        adr     x17, 0x556461ae94
   0x556461ae88:        br      x16
(gdb) x/g 0x556461ae8c
0x556461ae8c:   0x7fb78255a8 <ffi_closure_SYSV>
```
which is analogous, but `sigsegv`s at the second instruction (the one I marked with an asterisk).

Possibly related info can be found here:
- https://github.com/libffi/libffi/issues/262
- https://bugs.python.org/issue26942
- https://bugs.python.org/issue27606

So marking this as "won't fix". Sorry for the inconveniences.
